### PR TITLE
WIK-15 - 18 feat: add end screens

### PR DESCRIPTION
**Pull request by Colin-C32**
Levels End computer:
image
Levels End mobile:
image
Daily End Mobile:
image
Daily End Computer:
image
Rush End Computer: 
image
Rush End Mobile:
image

### CODE REVIEW

**Comment by Colin-C32** [comment]
Looking back I see that the Overlay on mobile might be a bit small so please let me know if this is an issue and I can upate it

**Comment by Colin-C32** [comment]
> Looking back I see that the Overlay on mobile might be a bit small so please let me know if this is an issue and I can upate it

Images are not fully accurate I increased the width of the overlay now

**Review by harrisonMondragon — APPROVED** [review]
LGTM

**Review by jmcmurtry — CHANGES_REQUESTED** [review]
All of the overlay popups look good on mobile screen sizes, but weird on large screens like a monitor. Needs some styling fixes. See attached images for examples:
overlay3
overlay2
overlay1

**Review by jmcmurtry — APPROVED** [review]

**Pull request merged**
