### PR TITLE
wik-62: remove rush overlays and fix rush errors

### PR DESCRIPTION
**Pull request by jmcmurtry**
After a discussion with Colin we decided to remove the rush overlays to improve the user experience and solve a bunch of refresh/async issues that were happening and make it feel like a more genuine "rush" style of game where the user cannot take a break.

Let me know what you think of the colors when a user presses skip or gets an answer correct.

### CODE REVIEW

**Review by Kjeon7 — APPROVED** [review]

**Comment by harrisonMondragon** [comment]
I think we should add a warning popup when no more skips are allowed

**Comment by harrisonMondragon** [comment]
I think 1min works better but that is easily changable

**Comment by harrisonMondragon** [comment]
I think if time runs out but there are still skips available, it should automatically use a skip and restart timer rather than ending game

**Review by harrisonMondragon — APPROVED** [review]
Comments addressed, lgtm

**Pull request merged**
