### PR TITLE
Wik65

### PR DESCRIPTION
**Pull request by Kjeon7**

### CODE REVIEW

**Review by jmcmurtry — CHANGES_REQUESTED** [review]
Can you move the change password and change username page into a separate folder within the admin so the route is like "admin/admin-settings/change-password" so that it is different from the normal user pages. You can probably just copy paste them. Then add the admin header to these two pages and should be good to go. Otherwise everything else looks super clean.

**Comment by Colin-C32** [comment]
Can we put a card around the rush settings here? 
image

**Comment by Colin-C32** [comment]
Also on rush settings screen it uses the normal user nav abr: 
image

**Comment by Colin-C32** [comment]
Also fix this: 
image

**Review by jmcmurtry — CHANGES_REQUESTED** [review]
Maybe we could reduce the size of the white box on the rush settings page so it is a bit tighter? Feels like a lot of whitespace. See attached image.

Also the burger menu dropdown doesnt feel responsive. I'm not sure how to describe it but if you play around with it and try to hover on the dropdown options, it feels like 75% of the time the hover isn't working and they aren't clickable. Not sure whats happening here. 

After these fixes are in we should be good to merge
Screenshot 2024-03-28 205132

**Review by jmcmurtry — APPROVED** [review]

**Pull request merged**
